
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Piyush G
 */
public class ALTER_SCHEDULE extends javax.swing.JFrame {
public static final String USERNAME= "root";
public static final String PASSWORD= "12345678";
public static final String CONN_STRING ="jdbc:mysql://localhost:3306/comp_ia?autoReconnect=true&useSSL=false";
public static Connection conn= null;
public static PreparedStatement pst =null;
public static ResultSet rs=null;
public static void MySQL() {
        try{
        conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);  
         } catch (SQLException e){
           }
    
}
    public ALTER_SCHEDULE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("PlayNow");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a sport", "Badminton", "Squash", "Basketball", "Football", "Swimming", "Table Tennis", "Tennis" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a slot", "6-7", "7-8", "8-9", "9-10", "10-11", "11-12", "12-13", "14-15", "15-16", "16-17", "17-18", "18-19", "19-20", "20-21", "21-22" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOKING"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
MySQL();
Object Sport=jComboBox2.getSelectedItem();
String Sport1=Sport.toString();
if (Sport1.equals("Badminton"))
{
        try{
String query3 ="Select BOOKING from Badminton";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else if (Sport1.equals("Squash"))
{
        try{
String query3 ="Select BOOKING from Squash";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else if (Sport1.equals("Football"))
{
        try{
String query3 ="Select BOOKING from football";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else if (Sport1.equals("Basketball"))
{
        try{
String query3 ="Select BOOKING from Basketball";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else if (Sport1.equals("Swimming"))
{
        try{
String query3 ="Select BOOKING from Swimming";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else if (Sport1.equals("Tennis"))
{
        try{
String query3 ="Select BOOKING from Tennis";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else if (Sport1.equals("Table Tennis"))
{
        try{
String query3 ="Select BOOKING from Table_Tennis";
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
} 
}
else
{
    JOptionPane.showMessageDialog(null,"Invalid entry");
}
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new ADMIN_SCREEN().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
private void Alter(String a, String b)
{
try{
String query2="Select SPORT from "+a+" where BOOKING='"+b+"'";
pst=conn.prepareStatement(query2); 
rs=pst.executeQuery();
if(rs.next()) 
{
    JOptionPane.showMessageDialog(null,"Slot already booked");
}  
else
{  try{
   String query =("insert into "+a+" values(?,?)");
   pst=conn.prepareStatement(query); 
   pst.setString(1, a);
   pst.setString(2, b);
   int i=pst.executeUpdate();
   if(i>0)
   {
   JOptionPane.showMessageDialog(null,"Booking made successfully");
   try{
String query3 ="Select BOOKING from " +a;
pst=conn.prepareStatement(query3); 
rs=pst.executeQuery();
Table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch (Exception e)
{
}
   }
   else{
     JOptionPane.showMessageDialog(null,"Booking not made successfully");
   }
}
catch(Exception E)
{
}    
        }
}
catch(Exception e)
{
    
}
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Object Sport=jComboBox2.getSelectedItem();
String Sport1=Sport.toString();
Object Slot=jComboBox3.getSelectedItem();
String Slot1=Slot.toString();
if (Slot1.equals("Choose a slot"))
{ JOptionPane.showMessageDialog(null,"Please choose a valid time slot.");
}
else{
if (Sport1.equals("Badminton"))
{
Alter(Sport1,Slot1);
}
else if (Sport1.equals("Squash"))
{
Alter(Sport1,Slot1);
}
else if (Sport1.equals("Basketball"))
{
Alter(Sport1,Slot1);
}
else if (Sport1.equals("Football"))
{
Alter(Sport1,Slot1);
}
else if (Sport1.equals("Swimming"))
{
Alter(Sport1,Slot1);
}
else if (Sport1.equals("Tennis"))
{
Alter(Sport1,Slot1);
}
else if (Sport1.equals("Table Tennis"))
{
Alter("Table_Tennis",Slot1);
}
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALTER_SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALTER_SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALTER_SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALTER_SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
          
           public void run() {
                
                new ALTER_SCHEDULE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
