import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Piyush G
 */
public class LEND_SCREEN extends javax.swing.JFrame {
public static final String USERNAME= "root";
public static final String PASSWORD= "12345678";
public static final String CONN_STRING ="jdbc:mysql://localhost:3306/comp_ia?autoReconnect=true&useSSL=false";
public static Connection conn= null;
public static PreparedStatement pst =null;
public static ResultSet rs=null;
public String Equipment1="";
public String Equipment2="";
public LEND_SCREEN() {
        initComponents();
    }
public void MySQL()
{
try{
        conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD); 
        
    }   catch (SQLException e){
                  }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        JT1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        JT2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("PlayNow");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE SPORT" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "LENDERS"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        MySQL();
        Object Sport=jComboBox2.getSelectedItem();
        String Sport1=Sport.toString();
        if (Sport1.equals("BADMINTON"))
        {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("CHOOSE EQUIPMENT");
            jComboBox1.addItem("SHUTTLE COCK");
            jComboBox1.addItem("BADMINTON RACKET");
            jComboBox1.addItem("BOTH");
            
        }
          
        
        else if (Sport1.equals("SQUASH"))
        { 
            jComboBox1.removeAllItems();
            jComboBox1.addItem("CHOOSE EQUIPMENT");
            jComboBox1.addItem("SQUASH RACKET");
            jComboBox1.addItem("SQUASH BALL");
            jComboBox1.addItem("BOTH");
           
        }
        else if (Sport1.equals("FOOTBALL"))
        {
           
            jComboBox1.removeAllItems();
            jComboBox1.addItem("CHOOSE EQUIPMENT");
            jComboBox1.addItem("FOOTBALL");
            
        }
        else if (Sport1.equals("BASKETBALL"))
        {
            
            jComboBox1.removeAllItems();
            jComboBox1.addItem("CHOOSE EQUIPMENT");
            jComboBox1.addItem("BASKETBALL");
        }
        else if (Sport1.equals("SWIMMING"))
        {
           
        }
        else if (Sport1.equals("TENNIS"))
        {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("CHOOSE EQUIPMENT");
            jComboBox1.addItem("TENNIS RACKET");
            jComboBox1.addItem("TENNNIS BALL");
            jComboBox1.addItem("BOTH");
        }
        else if (Sport1.equals("TABLE TENNIS"))
        {
         
            jComboBox1.removeAllItems();
            jComboBox1.addItem("CHOOSE EQUIPMENT");
            jComboBox1.addItem("TT RACKET");
            jComboBox1.addItem("TT BALL");
            jComboBox1.addItem("BOTH");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid entry");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
           String a=JT2.getText();
           String parts1[]=a.split(" ");
           String player=parts1[1];      
            Object Sport=jComboBox2.getSelectedItem();
            String Sport1=Sport.toString();
            Object temp= jComboBox1.getSelectedItem();
            Equipment1=temp.toString();
            Equipment2="";
            int d=0;
                       
            try{
            String query2 ="Select LENDING, FIRSTNAME from players where FIRSTNAME !='"+player+"'";
            pst=conn.prepareStatement(query2); 
            rs=pst.executeQuery();
            while (rs.next())
            {a=rs.getString("LENDING");
            String b= rs.getString("FIRSTNAME");
            String parts[]=a.split(",");
            if(Equipment1.equals("BOTH"))
            {
                if (Sport1.equals("BADMINTON"))
                {Equipment1="BADMINTON RACKET";
                Equipment2="SHUTTLE COCK";
                add(parts,Equipment1, Equipment2, d, b); 
                }
                if (Sport1.equals("SQUASH"))
                {Equipment1="SQUASH RACKET";
                Equipment2="SQUASH BALL";
                add(parts,Equipment1, Equipment2, d, b); 
                }
                if (Sport1.equals("TENNIS"))
                {Equipment1="TENNIS RACKET";
                Equipment2="TENNIS BALL";
                add(parts,Equipment1, Equipment2, d, b); 
                }
                if (Sport1.equals("TABLE TENNIS"))
                {Equipment1="TT RACKET";
                Equipment2="TT BALL";
                add(parts,Equipment1, Equipment2, d, b); 
                }
            }
            else{
            for (int i=0; i<parts.length; i++)
            { 
           if(parts[i].equals(Equipment1))
            {
            jTable2.setValueAt(b, d, 0);
            d=d+1;
            }
            }    
            }
            }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
int row= jTable2.rowAtPoint(evt.getPoint());
        String Lender= jTable2.getValueAt(row,0).toString();
        String Email="";
        String Name="";
        String Email2="";
        try{
            String query5="Select EMAIL from players where FIRSTNAME='"+Lender+"'";
            pst=conn.prepareStatement(query5);
            rs=pst.executeQuery();
            if(rs.next())
            {
                Email=rs.getString("EMAIL");
                String d=JT2.getText();
                String parts[]=d.split(" ");
                Name=parts[1];
                            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        try{
            String query6="Select EMAIL from players where FIRSTNAME='"+Name+"'";
            pst=conn.prepareStatement(query6);
            rs=pst.executeQuery();
            if(rs.next())
            {
                Email2=rs.getString("EMAIL");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        Mail(Email,Lender ,Name, Email2);
    }    
    public void Mail(String Email, String Lender, String Name, String Email2)
{   
    final String username="playnow.comp.ia@gmail.com";
    final String password="PlayNow123";
    Properties props=new Properties();
    props.put("mail.smtp.auth","true");
    props.put("mail.smtp.starttls.enable","true");
    props.put("mail.smtp.host","smtp.gmail.com");
    props.put("mail.smtp.port","587");
    Session session=Session.getInstance(props,
           new javax.mail.Authenticator(){
           
           protected PasswordAuthentication getPasswordAuthentication()
           {
               return new PasswordAuthentication(username,password);
           }
                
            });
    try{
        Message message=new MimeMessage(session);
        message.setFrom(new InternetAddress("playnow.comp.ia@gmail.com"));
        message.setRecipients(Message.RecipientType.TO,
        InternetAddress.parse(Email));
        message.setSubject("Borrow Request");
        if(!Equipment2.equals(""))
        {
        message.setText("Dear " + Lender +",\n\n"+ Name +" would like to borrow a "+Equipment1.toLowerCase()+" and a "+Equipment2.toLowerCase()+". Please reply with your decision to "+Email2+" \n\nRegards,\nPlayNow Team");
        }
        else 
        {
        message.setText("Dear " + Lender +",\n\n"+ Name +" would like to borrow a "+Equipment1.toLowerCase()+" . Please reply with your decision to "+Email2+" \n\nRegards,\nPlayNow Team");
        }
        Transport.send(message);
        JOptionPane.showMessageDialog(null,"An email has been sent to "+Lender+ " with details about required equipment. \nPlease check your email for further correspondence.");
        new LOGIN_SCREEN().setVisible(true);
        dispose();
        
    }
   catch (MessagingException e) {
			throw new RuntimeException(e);
		}
}

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new PLAY_SCREEN().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new LOGIN_SCREEN().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    
    public void add(String parts[],String Equipment1, String Equipment2, int d, String b)
{
      for (int i=0; i<parts.length; i++)
            { 
            if(parts[i].equals(Equipment1))
            { for (i=0; i<parts.length; i++)
            {if(parts[i].equals(Equipment2))
            {jTable2.setValueAt(b, d, 0);
            d=d+1;
            }
            }
            }
            } 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEND_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEND_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEND_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEND_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEND_SCREEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel JT1;
    public static javax.swing.JLabel JT2;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
